## creando nuevo usuario incorrecto
POST http://localhost:8090/auth/nuevo HTTP/1.1
Content-Type: application/json

{
    "nickname": "prueba",
    "email": "@",
    "password": "a",
    "roles": ["admin"]
}

###
## creando nuevo usuario
POST http://localhost:8090/auth/nuevo HTTP/1.1
Content-Type: application/json

{

    "nickname": "alex",
    "nombre": "Alex Garcia",
    "email": "alexgarcia@gmail.com",
    "password": "NoTeLoDigo@1",
    "roles": [""]
}

###
## login ok
POST http://localhost:8090/auth/login HTTP/1.1
Content-Type: application/json

{

    "nickname": "jaumet",
    "password": "NoTeLoDigo@1"
}

###
##  con JWGT (admin)
GET http://localhost:8090/api/v1/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqYXVtZXQiLCJpYXQiOjE3MDgwMTk2MDQsImV4cCI6MTcwODA1NTYwNH0.jCICbS6qGWY3NjTpr1XBZS_CcJ6Y0PNGt90ci9OS8sc
###
##  con JWGT (user)
GET http://localhost:8090/api/v1/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqYXVtZXQiLCJpYXQiOjE3MDgwMTk2MDQsImV4cCI6MTcwODA1NTYwNH0.jCICbS6qGWY3NjTpr1XBZS_CcJ6Y0PNGt90ci9OS8sc

### USUARIOS ###

###

##  getUsuarioInfoById: Para el perlfil del usuario

GET http://localhost:8090/api/v1/jaumet/profile HTTP/1.1 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqYXVtZXQiLCJpYXQiOjE3MDgwMTk2MDQsImV4cCI6MTcwODA1NTYwNH0.jCICbS6qGWY3NjTpr1XBZS_CcJ6Y0PNGt90ci9OS8sc###
###

## getJugadorInfoByNickname: Para las estadisticas del jugador. Tambien mostrara una lista de tableros que ha creado un jugador
GET http://localhost:8090/api/v1/jaumet/estadisticas HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqYXVtZXQiLCJpYXQiOjE3MDgwMTk2MDQsImV4cCI6MTcwODA1NTYwNH0.jCICbS6qGWY3NjTpr1XBZS_CcJ6Y0PNGt90ci9OS8sc###
###


###
## Editar el perfil de un Usuario
PUT http://localhost:8090/auth/update/jaumet HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqYXVtZXQiLCJpYXQiOjE3MDgwMTk2MDQsImV4cCI6MTcwODA1NTYwNH0.jCICbS6qGWY3NjTpr1XBZS_CcJ6Y0PNGt90ci9OS8sc


{
    "nombre": "jaume",
    "nickname": "jaumet",
    "email": "jaume@gmail.com"
}
###

## getJugadores: Para el ranking 
GET http://localhost:8090/api/v1/ranking HTTP/1.1
Content-Type: application/json
###


## Crear Tablero // TODAVIA NO ESTA OPERATIVA
POST http://localhost:8090/api/v1/crear-tablero HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqYXVtZXQiLCJpYXQiOjE3MDgwMTk2MDQsImV4cCI6MTcwODA1NTYwNH0.jCICbS6qGWY3NjTpr1XBZS_CcJ6Y0PNGt90ci9OS8sc

{
    "id_jugador": "jaumet",
    "titulo": "Partida Jaume",
    "finalizada": "1"
}

###
## Listar los tableros
GET http://localhost:8090/api/v1/tableros HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqYXVtZXQiLCJpYXQiOjE3MDgwMTk2MDQsImV4cCI6MTcwODA1NTYwNH0.jCICbS6qGWY3NjTpr1XBZS_CcJ6Y0PNGt90ci9OS8sc
###

## deleteByIdCity
DELETE http://localhost:8090/auth/delete/josera HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqYXVtZXQiLCJpYXQiOjE3MDgwMTk2MDQsImV4cCI6MTcwODA1NTYwNH0.jCICbS6qGWY3NjTpr1XBZS_CcJ6Y0PNGt90ci9OS8sc
###

## updateTablero
PUT http://localhost:8090/api/v1/tablero/2 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqYXVtZXQiLCJpYXQiOjE3MDgwMTk2MDQsImV4cCI6MTcwODA1NTYwNH0.jCICbS6qGWY3NjTpr1XBZS_CcJ6Y0PNGt90ci9OS8sc

{
    "id": 2,
    "id_jugador": "jaumet",
    "titulo": "Primera 2",
    "finalizada": "0"
}
###