## creando nuevo usuario incorrecto
POST http://localhost:8090/auth/nuevo HTTP/1.1
Content-Type: application/json

{
    "nickname": "prueba",
    "email": "@",
    "password": "a",
    "roles": ["admin"]
}

###
## creando nuevo usuario
POST http://localhost:8090/auth/nuevo HTTP/1.1
Content-Type: application/json

{

    "nickname": "Alex",
    "nombre": "Alex Garcia",
    "email": "alex@gmail.com",
    "password": "NoTeLoDigo@1",
    "roles": ["admin"]
}

###
## login ok
POST http://localhost:8090/auth/login HTTP/1.1
Content-Type: application/json

{

    "nickname": "Pedro",
    "password": "NoTeLoDigo@1"
}

###
##  con JWGT (admin)
GET http://localhost:8090/api/v1/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJQZWRybyIsImlhdCI6MTcwODQ3Njg2NCwiZXhwIjoxNzA4NTEyODY0fQ.C1Z24XEjfoFtiyvMSa6tqYiO7_wMg2RaotE8CoInAVc
###
##  con JWGT (user)
GET http://localhost:8090/api/v1/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJQZWRybyIsImlhdCI6MTcwODQ3Njg2NCwiZXhwIjoxNzA4NTEyODY0fQ.C1Z24XEjfoFtiyvMSa6tqYiO7_wMg2RaotE8CoInAVc

### USUARIOS ###

###

##  getUsuarioInfoById: Para el perlfil del usuario

GET http://localhost:8090/api/v1/Pepe/profile HTTP/1.1 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJQZWRybyIsImlhdCI6MTcwODQ3Njg2NCwiZXhwIjoxNzA4NTEyODY0fQ.C1Z24XEjfoFtiyvMSa6tqYiO7_wMg2RaotE8CoInAVc###
###

## getJugadorInfoByNickname: Para las estadisticas del jugador. Tambien mostrara una lista de tableros que ha creado un jugador
GET http://localhost:8090/api/v1/Pepe/estadisticas HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJQZWRybyIsImlhdCI6MTcwODQ3Njg2NCwiZXhwIjoxNzA4NTEyODY0fQ.C1Z24XEjfoFtiyvMSa6tqYiO7_wMg2RaotE8CoInAVc###
###


###
## Editar el perfil de un Usuario
PUT http://localhost:8090/auth/update/Pepe HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJQZWRybyIsImlhdCI6MTcwODQ3Njg2NCwiZXhwIjoxNzA4NTEyODY0fQ.C1Z24XEjfoFtiyvMSa6tqYiO7_wMg2RaotE8CoInAVc


{
    "nombre": "pepito",
    "nickname": "Pepe",
    "email": "pepito@gmail.com"
}
###

## getJugadores: Para el ranking 
GET http://localhost:8090/api/v1/ranking HTTP/1.1
Content-Type: application/json
###


## Crear Tablero y jugador_en_sala
POST http://localhost:8090/api/v1/crear-tablero HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJQZWRybyIsImlhdCI6MTcwODQ3Njg2NCwiZXhwIjoxNzA4NTEyODY0fQ.C1Z24XEjfoFtiyvMSa6tqYiO7_wMg2RaotE8CoInAVc

{
    "id_jugador": "Pepe",
    "titulo": "Partida Prueba",
    "finalizada": "1"
}

###
## Listar los tableros
GET http://localhost:8090/api/v1/tableros HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJQZWRybyIsImlhdCI6MTcwODQ3Njg2NCwiZXhwIjoxNzA4NTEyODY0fQ.C1Z24XEjfoFtiyvMSa6tqYiO7_wMg2RaotE8CoInAVc
###

## deleteByIdCity
DELETE http://localhost:8090/auth/delete/Edu HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJQZWRybyIsImlhdCI6MTcwODQ3Njg2NCwiZXhwIjoxNzA4NTEyODY0fQ.C1Z24XEjfoFtiyvMSa6tqYiO7_wMg2RaotE8CoInAVc
###

## updateTablero
PUT http://localhost:8090/api/v1/tablero/6 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJQZWRybyIsImlhdCI6MTcwODQ3Njg2NCwiZXhwIjoxNzA4NTEyODY0fQ.C1Z24XEjfoFtiyvMSa6tqYiO7_wMg2RaotE8CoInAVc

{
    "id": 2,
    "id_jugador": "Pepe",
    "titulo": "Primera 2",
    "finalizada": "0"
}

###
## Jugador sala
GET http://localhost:8090/api/v1/jugadorSala/16/info HTTP/1.1 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJQZWRybyIsImlhdCI6MTcwODQ3Njg2NCwiZXhwIjoxNzA4NTEyODY0fQ.C1Z24XEjfoFtiyvMSa6tqYiO7_wMg2RaotE8CoInAVc

###
## Tablero Info
GET http://localhost:8090/api/v1/tablero/11/info HTTP/1.1 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJQZWRybyIsImlhdCI6MTcwODQ3Njg2NCwiZXhwIjoxNzA4NTEyODY0fQ.C1Z24XEjfoFtiyvMSa6tqYiO7_wMg2RaotE8CoInAVc

###
## Unirse
POST http://localhost:8090/api/v1/unirse-tablero/10/Alex HTTP/1.1 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJQZWRybyIsImlhdCI6MTcwODQ3Njg2NCwiZXhwIjoxNzA4NTEyODY0fQ.C1Z24XEjfoFtiyvMSa6tqYiO7_wMg2RaotE8CoInAVc